version: '3.8'

services:
  # Development environment with mounted source
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace
      - cargo_cache:/home/dev/.cargo
      - target_cache:/workspace/target
    working_dir: /workspace
    tty: true
    stdin_open: true
    environment:
      - RUST_BACKTRACE=1
      - CARGO_TERM_COLOR=always
    command: /bin/bash
    
  # CI simulation environment
  ci:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/workspace:ro  # Read-only to simulate CI
    working_dir: /workspace
    environment:
      - CI=true
      - RUST_BACKTRACE=1
    command: >
      bash -c "
        cargo fmt --all -- --check &&
        cargo clippy --all-targets --all-features -- -D warnings &&
        cargo test --quiet &&
        ./run_tests.sh
      "

volumes:
  cargo_cache:
  target_cache: